definitions:
  entity.Task:
    properties:
      description:
        type: string
      id:
        description: UUID
        type: string
      status:
        description: '0: 未着手, 1: 完了'
        type: integer
      title:
        type: string
    type: object
info:
  contact: {}
  description: TODOリストアプリのRESTfulAPI（Go実装）
  title: TodoList API
  version: "1.0"
paths:
  /v1/tasks/{id}:
    get:
      description: ユーザのタスクを1件取得する
      parameters:
      - description: タスクID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Task'
      summary: タスク取得（1件）
      tags:
      - task
swagger: "2.0"
x-order: 1
